# Generated by Django 4.2.27 on 2025-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(help_text='Markdown content for the post')),
                ('excerpt', models.TextField(blank=True, help_text='Short description of the post', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=True)),
                ('category', models.CharField(default='General', help_text="Category like 'CTF Writeup', 'Blog Post', etc.", max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
