# Generated by Django 6.0 on 2026-01-21 18:11

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the item', null=True, upload_to=main.models.item_image_upload_path),
        ),
    ]
